version: "3.9"
services:
  postgres:
    image: postgres:alpine3.19
    env_file:
      - .env
    environment:
      POSTGRES_DB: "postapp"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postapp-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postapp-data: