#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/postapp
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=jdbc:h2:mem:postapp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

server.port=8081