spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/postapp
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.schemas=public
spring.flyway.locations=classpath:/migrations