#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/postapp
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=jdbc:h2:mem:postapp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server.port=8081

spring.flyway.schemas=public
spring.flyway.locations=classpath:/migrations